from juego import puntos
from juego import carta
from juego import mazo
from juego import player

def main():
	puntosCarta1 = puntos.Puntos(10, 6, 9, 4)
	puntosCarta2 = puntos.Puntos(5, 3, 9, 10)
	carta1 = carta.CartaMonstruo("Squall", "", "", puntosCarta1)
	carta2 = carta.CartaMonstruo("Laguna", "", "", puntosCarta2)
	Mazo1 = mazo.Mazo()
	Mazo1.agregarcarta(carta1)
	Mazo1.agregarcarta(carta2)
	p1 = player.Player("Pepe", Mazo1)
	print("Mano: ")
	print(p1.getmano())
	print("---------")
	print("Deck")
	print(p1.deck)
	print()
	print("¡ROBA!")
	p1.robar()
	print()
	print("Mano: ")
	print(p1.getmano())
	print("---------")
	print("Deck")
	print(p1.deck)
	print()
	print("------------------------------")
	print()
	puntosCarta3 = puntos.Puntos(9, 9, 2, 3)
	puntosCarta4 = puntos.Puntos(6, 6, 3, 2)
	puntosCarta5 = puntos.Puntos(9, 2, 8, 6)
	carta3 = carta.CartaMonstruo("Mogurito", "", "", puntosCarta3)
	carta4 = carta.CartaMonstruo("Cactilio", "", "", puntosCarta4)
	carta5 = carta.CartaMonstruo("Ifrit", "", "Fuego", puntosCarta5)
	Mazo2 = mazo.Mazo()
	Mazo2.agregarcarta(carta1)
	Mazo2.agregarcarta(carta2)
	Mazo2.agregarcarta(carta3)
	Mazo2.agregarcarta(carta4)
	Mazo2.agregarcarta(carta5)
	print(Mazo2)
	Mazo2.mezclar()
	print("---------- MEZCLA ----------")
	print(Mazo2)

if __name__ == "__main__":
    main()