package main

import (
	"fmt"
	"modulo/juego"
)

func main() {
	puntosCarta1 := juego.NewPuntos(10, 6, 9, 4)
	puntosCarta2 := juego.NewPuntos(5, 3, 9, 10)
	carta1 := juego.NewCarta(puntosCarta1, "Squall", "")
	carta2 := juego.NewCarta(puntosCarta2, "Laguna", "")
	Mazo1 := juego.NewMazo()
	Mazo1.AgregarCarta(carta1)
	Mazo1.AgregarCarta(carta2)
	p1 := juego.NewPlayer("Pepe", Mazo1)
	fmt.Println("Mano: ")
	fmt.Println(fmt.Sprint(p1.GetMano()))
	fmt.Println("---------")
	fmt.Println("Deck")
	fmt.Println(p1.GetDeck().String())
	fmt.Println()
	fmt.Println("¡ROBA!")
	p1.Robar()
	fmt.Println()
	fmt.Println("Mano")
	fmt.Println(fmt.Sprint(p1.GetMano()))
	fmt.Println("---------")
	fmt.Println("Deck")
	fmt.Println(p1.GetDeck().String())
	fmt.Println()
	fmt.Println("------------------------------")
	fmt.Println()
	puntosCarta3 := juego.NewPuntos(9, 9, 2, 3)
	puntosCarta4 := juego.NewPuntos(6, 6, 3, 2)
	puntosCarta5 := juego.NewPuntos(9, 2, 8, 6)
	carta3 := juego.NewCarta(puntosCarta3, "Mogurito", "")
	carta4 := juego.NewCarta(puntosCarta4, "Cactilio", "")
	carta5 := juego.NewCarta(puntosCarta5, "Ifrit", "")
	Mazo2 := juego.NewMazo()
	Mazo2.AgregarCarta(carta1)
	Mazo2.AgregarCarta(carta2)
	Mazo2.AgregarCarta(carta3)
	Mazo2.AgregarCarta(carta4)
	Mazo2.AgregarCarta(carta5)
	fmt.Println(Mazo2.String())
	Mazo2.Mezclar()
	fmt.Println("---------- MEZCLA ----------")
	fmt.Println(Mazo2.String())
}
